### ISSUE TITLE
Add Image to a column

### ISSUE THREAD

**Issue by dj-fiorex** [wobkenh/simplematcomponents#11]
Hi, first of all thanks for this beautiful astraction of mat-table! I have a question: how can i add an image to a column?
Thanks

**Comment by wobkenh** [comment]
It is possible to set the background image of a cell using ngStyle. TableColumn has an option called setNgStyle, which allows you to return a ngStyle Object based on the data of the cell/row. You could then use the background css property to specify the background image. This means that you have all the css tools for background image configuration at your disposal (e.g. background-position, background-repeat, background-size, ...), just add the css properties you need to the ngStyle object.

Here is a minimalistic example:
```
const imageCol = new TableColumn<ComplexTestData, 'description'>('Description', 'description')
    .withTransform(() => '') // To hide the text in the cell
    .withNgStyle(() => {
        return {
          'background': 'url(<imgUrl>)',
          'background-size': 'contain',
          'background-repeat': 'no-repeat'
        };
      })
```
You could also define a css class with all the background properties and set the class via TableColumns withNgClass method. In that case, you would only have to use withNgStyle for the background property if your imgUrl depends on the cell/row data.

It is, however, not possible right now to change the height of a cell other than by filling it with a large text or a text area with a lot of lines (please dont). This could make it hard to get pictures to show in a large enough size. A solution to this problem would be to create a height/minHeight property on TableColumn. Another solution would be a new TableColumn function property to set an image based on cell data. I could use the resulting url to create a html <img> tag. But that would mean that all the background-properties could not be used anymore. 

Right now im tending toward the height/minHeight property. I will look into this to see how this can be achieved without interfering with mat-table and without breaking existing simplemattable features. Maybe you can get by for now with the solution i provided above.

**Comment by wobkenh** [comment]
So i just had some time to look into the issue.
The best solution in my opinion would be to stop using flex directly on table cells (td as well as th), so the table cells keep their default display property (value: table-cell). Then, we could apply height/width as needed on the table cells. To position content in the cell, we could then use a div inside the table cell with display: flex.

I tried this out on a new branch (row-height) and it seems to work. However, some existing features of mattable do not yet work with the new solution, e.g. changing the visibility of columns. The changes cannot be merged into the master branch until those problems have been addressed accordingly and all features have been tested thoroughly. 

I am currently pretty busy with another project, so I do not now when I will have time to work on simplemattable. If anyone wants to help, feel free to checkout the branch row-height.

**Comment by dj-fiorex** [comment]
Thanks for your time! In fact i went with 
```javascript
new TableColumn<OrderData, 'delivery'>('Delivery', 'delivery')
            .withTransform((data) => '')
            .withNgClass((data) => 'je-logo-background')
            .withWidth('15vw')
```

and 
```scss
.je-logo-background {
  background-image: url("assets/logo/logo.png");
  background-repeat: no-repeat;
  background-size: contain;
}
```

Thanks for your perfect explanation, i will watch for row-height branch.

Meanwhile i have a simple question: how can i reset the text in the filter input from code (like when a button is clicked)?

Thanks a lot again

**Comment by wobkenh** [comment]
Up until now it was not possible to set the column filter input text. But since it was quite easy to implement, I just went ahead and implemented it :). I added a new method to the TableColumn called setColFilterText. You can use this to set the text of the column filter input.

To use this feature, update simplemattable to 1.6.1.

**Comment by wobkenh** [comment]
FYI: It is now possible to set the height of a column using the height function. So should you (or anyone stumbling over this github issue) desire to display bigger images, you can now do so by increasing the row height and then using the ngStyle function as mentioned above to set a background image. Examples for cell height and background images are available [in the new demo application](https://simplex24.de/smc-demo/).
