### ISSUE TITLE
simplemattable: filter row

### ISSUE THREAD

**Issue by snebjorn** [wobkenh/simplematcomponents#4]
I'd love support for a something like a filter row that can filter each column individually.

**Comment by wobkenh** [comment]
Sorry that it took me so long to answer. 
Your idea is good. I'm on it.

**Comment by wobkenh** [comment]
I just pushed version 1.5 of simplemattable. Using `withColFilter()` on a table column will now generate an input below the column header. Sadly, there is a bug where if you use sorting + column headers, the sorting direction will change while being in the column filter input. I could not figure out how to stop the key event from propagating.

I'm closing this issue. If you have any questions, feedback or ideas, feel free to reopen this issue or to create a new one.

**Comment by WGriffing** [comment]
I may have a lead on the space bar causing sort direction to toggle while typing in a column filter.

I modified the applyColFilter function to accept the event (shown below) and the template to pass the $event (not shown) to the function.

```
    SimplemattableComponent.prototype.applyColFilter = /**
     * @return {?}
     */
    function (event) {
        /** @type {?} */
        var len = this.dataSource.filter.length - 1;
        if (this.dataSource.filter.charAt(len) !== ' ') {
            this.dataSource.filter = (this.dataSource.filter + ' ');
        }
        else {
            this.dataSource.filter = this.dataSource.filter.substring(0, len);
        }
        if (this.dataSource.filter === '') {
            this.dataSource.filter = '  ';
        }
        event.preventDefault();
    };
```

I added a single line, "event.preventDefault()", at the end of the applyColFilter method. I have not done any exhaustive testing at this point to check for other negative effects, but the sort no longer changes direction when I type a space in a column filter.
