### ISSUE TITLE
making page so slow

### ISSUE THREAD

**Issue by keyone2693** [wobkenh/simplematcomponents#42]
in every page that I use this the other controls like input select 
working so slowly
and I keep getting this warnings

![5555](https://user-images.githubusercontent.com/19763704/71783184-59033a00-2ff8-11ea-9ba7-4061b974f2a7.PNG)

**Comment by Auricopter** [comment]
I noticed that if I have 14 Columns I get very bad performance if I show 10 or more Rows at the same time. 
If I only have 7 Columns it's fine.
Why is that?

**Comment by keyone2693** [comment]
there is a lot of thing going on with onfocus onclick and setinterval,.. !!!

**Comment by wobkenh** [comment]
I can't reproduce this problem if i just add a lot of columns and some data items to a table.
I have also never had warning from setTimeout/setInternval/requestAnimationFrame.

Could you please provide me with an example? This goes for both of you. Please show me: 

- how you defined the simplemattable in the html
- what your table columns in typescript look like
- what your model in typescript looks like
- how many items will be displayed in the table at a time

With this information, I will be able to analyse the problem further and maybe I can the find the reason for the poor performance you are getting.

**Comment by keyone2693** [comment]
currently, im using a table with pagination .i fork your project
and remove loading, form-controls, add-edit-delete, buttons functionality

and now it's working perfectly

**Comment by Auricopter** [comment]
> I can't reproduce this problem if i just add a lot of columns and some data items to a table.
> I have also never had warning from setTimeout/setInternval/requestAnimationFrame.
> 
> Could you please provide me with an example? This goes for both of you. Please show me:
> 
> * how you defined the simplemattable in the html
> * what your table columns in typescript look like
> * what your model in typescript looks like
> * how many items will be displayed in the table at a time
> 
> With this information, I will be able to analyse the problem further and maybe I can the find the reason for the poor performance you are getting.

I use Reactive Forms and my 14 Columns consist of TextFormFields, NumberFormFields, DateFormFields, CheckboxFormFields and SelectFormFields. The more I have the worse the performance gets. No matter which ones.

My HTML
`            <smc-simplemattable [data]="viewData" [columns]="columns" [sorting]="true" [sticky]="true" [editable]="true"
                [deletable]="false" [addable]="true" [paginator]="true" (add)="rowAddSave($event)" (edit)="rowEdit($event)"
                [create]="rowCreate" class="fee-table"></smc-simplemattable>`

Example Column Model
`        const aktivColumn = new TableColumn<ViewModel, 'aktiv'>('Aktiv', 'aktiv');
        aktivColumn.withIcon(data => data ? 'check_box' : 'check_box_outline_blank');
        aktivColumn.withTransform(data => "");
        const aktivColumnInput = aktivColumn.getCheckboxFormField();
        aktivColumn.withFormField(aktivColumnInput);`

More than 70 items in the table at a time slows the entire page down.

**Comment by wobkenh** [comment]
Okay, so I had a look and could reproduce your problem.

First of all, simplemattable is always going to be slower than if you implement the table yourself. A lot of checks have to be done since simplemattable has a lot of options. However, potential for performance upgrades is definitely there. For example, objects for ngStyle and ngClass are recalculated on every check. One could create at least some of the styles only on changes to the table columns and use the objects generated there in the html.

I can not tell you right now when I will have time to implement any of the performance improvements.

Regarding what keyone wrote: Removing FormControls and Buttons allows you to get rid of quite some checks, so it makes sense that this improves performance.

**Comment by Auricopter** [comment]
Thanks for checking. 
Another nice addition would be to be able to customize the paginator to limit the number rows. E.g. force the paginator to always show 5 entries per page.
Maybe for other use cases its also nice to be able to have custom number of entries in the paginator-dropdown-box. E.g. 50 entries per page.

**Comment by wobkenh** [comment]
You can use the `paginatorPageSizeOptions` option on simplemattable to achieve that.
It accepts an array of numbers, so if you want to limit the page size to 5 without other options, you can pass `[5]` to it.

**Comment by wobkenh** [comment]
I just released a new update `4.0` of simplemattable. With this version, I am able to display a table with editing enabled with 50 columns and 20 entries with just small lags. Before, 20 columns were already unusable. I made a before-after comparison on all cases of the [demo application](https://simplex24.de/smc-demo/) and the behavior seems to be the same, so I hope i broke nothing. Tests also still work.

Would you like to try out the new version and report back if it gave you any performance improvements or not?

**Comment by keyone2693** [comment]
tank U 
i will test it

**Comment by Auricopter** [comment]
We're gonna test it too tomorrow. :)

**Comment by Auricopter** [comment]
Thank you. Performance is fine now.

**Comment by keyone2693** [comment]
Just tested
It's fine now tanks

**Comment by wobkenh** [comment]
Perfect :)
