### ISSUE TITLE
Re-order columns by drag & drop

### ISSUE THREAD

**Issue by fuerst** [wobkenh/simplematcomponents#48]
Hi, 

first - thanks for simplematcomponents! It really helps implementing tables faster.

One question though: Did you consider implementing re-ordering of columns by drag & drop like it is demoed at https://material.angular.io/components/table/examples?

**Comment by wobkenh** [comment]
I will try to implement it this weekend.

**Comment by wobkenh** [comment]
I just released version 5.1.0 of simplemattable. You can now use the input parameter `columnDragAndDrop` to enable reordering columns by drag and drop.

Give it a try and tell me what you think :)

**Comment by fuerst** [comment]
Works really well, thanks a lot!
