### ISSUE TITLE
Footer row

### ISSUE THREAD

**Issue by fuerst** [wobkenh/simplematcomponents#49]
MatTable does have a MatFooterCellDef directive which can be used to display a sum or other calculation results below every column. It works by defining a `mat-footer-cell` at every column definition as well as one `mat-footer-row`. Do you have plans for implementing this feature?

**Comment by wobkenh** [comment]
Thank you for the suggestion :)
I will try to implement this over the course of the next few days.

**Comment by wobkenh** [comment]
I just released version 5.3 of simplemattable.
You can now add a footer using the `withFooter` method of `TableColumn`.

For an example, head over to the demo application (which also got a new look):
https://simplex24.de/smc-demo/footer

**Comment by fuerst** [comment]
Works nicely, thanks a lot! 
Your demo site is very helpful, by the way.
